# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a71e7ae7d7982d52823db631930cc13aac7d001a3b443cc63f002aa54e915d316a7bad09d82ac9994dcd058b74280d7211fddaf8c5eb7b358d076af83f4cef48

test:
  secret_key_base: da023491789bf7f0c6ee0a91add802119cdde52e4e1641e2307a7ba07597a31f393a4caceff0a45079f353d0f7b4d40a73d3b7434cfc2d851ea07f3591cf72b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
